{% set name = "xdesign" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomography/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a79364c7d98996290cbde4d4c2a26b2ea17a7a65af5a11c56a0143ee0a1e7a97

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - cached-property
    - matplotlib-base
    - numpy
    - python >=3
    - scipy

test:
  imports:
    - xdesign
    - xdesign.geometry
    - xdesign.metrics
    - xdesign.phantom

about:
  home: http://xdesign.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Benchmarking and optimization tools for tomography.'
  description: |
    XDesign is an open-source Python package for creating x-ray imaging
    phantoms, simulating data acquisition, and benchmarking x-ray
    tomographic image reconstruction.
  doc_url: https://xdesign.readthedocs.io
  dev_url: https://github.com/tomography/xdesign

extra:
  recipe-maintainers:
    - carterbox
