travis:
  secure:
    BINSTAR_TOKEN: DAKXZYkg/QiHVr06st7j/RJLmJZ4DIUNE7ci4Q88/u3QYrwe3y7Mxirm/XOLOb5Nfce573+mkYRsGjOTvnmf9/UdFh3XykpTyO7jk2IpWWvX+r/+e/jd6EZgtmCQ9xWJeizTn/PYyYvHBnLyadX2jqEwX2NK2qqgp53Xfh0ahFZY7NsTIhJEXx1YCmVQUJFteOTROs0YT5DzzuqEH2Zljgqp6vJ+UJFihipGpc9E6q+l02rl15A3cDQ3CsiIzCrF6h0Nnhtn2lOVJ/pBXeAdDXHGelca5ZLkHDzmqpzPH1Bu7mMI93cFJ9PNzNRg+1AdqXIYgpViXNuNqKsJh76JIQtFcunY24NNofJsguEdfgz0Uz7Cvc/aDr5fXahtf1Uz5W2ynNttllA6Ow0PLxZ08S3cBi3C3dzQQpkvOxlLzhiE1Qi7kyWH7oX9r2nHSif8hG2VoVlcMH6cH15QJZZf7ULDOrjakE1DCijzV7F2Qrh/GaNFuA1LhCJ71H9TqzFWoDopug7eaJVaQiVpnlol164TOv9clfw4Zi6TtGAlsMn7NtrSo4xmUKsm0DflHysjiHwVcltbEiUjsrMzUbJ3gl9H66BGkju2bXh7a6sTt4kyoLYMSQFUSfg+hHoYc1JyG/XjnOtY5q9pmjqjopX8ErY4sMIgRS2gXGFIH83Pry8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
